### ISSUE TITLE
11月14日开始 selenium TimeOutException

### ISSUE THREAD

**Issue by zyHan2077** [Bruuuuuuce/PKUAutoSubmit#38]
之前一直正常，今天早上没有报备成功，输出信息如下：

```
环境检查通过
Driver Launched

读取到1份配置文件

||第1个学生备案||
门户登陆中...
门户登录成功！
=================================
开始填报出校备案
选择出校/入校    Done
选择校区    Done
填写出入校事由    Done
选择出校目的地    Traceback (most recent call last):
  File "main.py", line 62, in <module>
    go('config.ini')
  File "main.py", line 38, in go
    run(driver_pjs, userName, password, campus, reason, destination, track,
  File "/home/zao/Desktop/Doing/PKUAutoSubmit/func.py", line 247, in run
    fill_out(driver, campus, reason, destination, track)
  File "/home/zao/Desktop/Doing/PKUAutoSubmit/func.py", line 171, in fill_out
    select_destination(driver, destination)
  File "/home/zao/Desktop/Doing/PKUAutoSubmit/func.py", line 102, in select_destination
    WebDriverWait(driver, 10).until(
  File "/home/zao/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by Housyou** [comment]
我也出现了这个问题，在[另一个仓库](https://github.com/xiazhongyv/PKUAutoSubmit_online/issues/1)里有提到这个超时问题，但当时说已经修复了，不知道究竟是为什么。

**Comment by Housyou** [comment]
0:01的时候是失败的，但我刚刚（8:00）的时候试了一次又成功了，怀疑是每天晚上到次日凌晨有一段时间网络不好

**Comment by Bruuuuuuce** [comment]
应该是网络环境的问题，请尝试定时在其他时间

**Comment by Theia-4869** [comment]
这个就是因为门户改了报备流程的原因，按照最新提交的代码库修改就可以了

**Comment by yanyuandaxia** [comment]
按照下面这位大佬的方式修改，增加邮箱、手机、出入校详细事由三个内容就行
https://github.com/xiazhongyv/PKUAutoSubmit_online
我已经改好了
https://github.com/yanyuandaxia/PKUAutoSubmit
