### ISSUE TITLE
selenium TimeoutException

### ISSUE THREAD

**Issue by hheei** [Bruuuuuuce/PKUAutoSubmit#41]
11月18日开始这样﹐之前试过也没啥问题﹐在本地运行也没问题﹐但放上action弄就一直超时了﹐不知道是不是我操作上的错误？
WebDriverWait那个原本是10的﹐出错了几次我试过自己改成60﹐但还是没作用。
麻烦作者了。
```
Run python3 main.py
Traceback (most recent call last):
  File "/home/runner/work/PKUAutoSubmit/PKUAutoSubmit/main.py", line 75, in <module>
    go(config)
  File "/home/runner/work/PKUAutoSubmit/PKUAutoSubmit/main.py", line 43, in go
    run(driver_pjs, userName, password, campus, reason, detail, destination, track,
  File "/home/runner/work/PKUAutoSubmit/PKUAutoSubmit/func.py", line 264, in run
    fill_out(driver, campus, reason, detail, destination, track)
  File "/home/runner/work/PKUAutoSubmit/PKUAutoSubmit/func.py", line 191, in fill_out
    submit(driver)
  File "/home/runner/work/PKUAutoSubmit/PKUAutoSubmit/func.py", line 155, in submit
    WebDriverWait(driver, 60).until(
  File "/usr/share/miniconda/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Screenshot: available via screen

环境检查通过
Driver Launched

读取到1份配置文件

||第1个学生备案||
门户登陆中...
Retrying...
门户登陆中...
门户登录成功！
=================================
开始填报出校备案
选择出校/入校    Done
选择校区    Done
填写出入校事由    Done
填写出入校事由详细描述    Done
选择出校目的地    Done
填写出校行动轨迹    Done
Error: Process completed with exit code 1.
```

**Comment by Bruuuuuuce** [comment]
感谢issue，看起来是在出校确认提交的环节出现了问题，具体的我由于无法使用系统无从得知，请查看一下与之前的流程是否有区别，或等待其他在校同学的解决，谢谢

**Comment by mickelliu** [comment]
写个try and except吧
